/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import model.VagasEmpregos;
import model.DaoVagas;
import model.Empresas;

/**
 *
 * @author mayara
 */
public class MayaJobs extends javax.swing.JFrame {
    VagasEmpregos vagas;
    DaoVagas daoVagas;
    /**
     * Creates new form MayaJobs
     */
    public MayaJobs() {
        initComponents();
        daoVagas = new DaoVagas();
        this.atualizarTabela();
       
    }
    public void atualizarTabela(){
        jTabela.setModel(new MayaJobsTableModel(daoVagas.buscarTodos()));
    }
    
    public void limparCampos(){
        tfCodigo.setText("");
        tfCargo.setText("");
        tfRequisitos.setText("");
        tfSalario.setText("");
        tfCodEmp.setText("");
        tfNome.setText("");
        tfFuncionarios.setText("");
        tfDescricao.setText("");
        tfFiltro.setText("");
        grupoBotao.clearSelection();
        
        btnExcluir.setEnabled(false);
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotao = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLMayaJobs = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabela = new javax.swing.JTable();
        tfCodigo = new javax.swing.JTextField();
        tfCargo = new javax.swing.JTextField();
        tfRequisitos = new javax.swing.JTextField();
        jLCodigo = new javax.swing.JLabel();
        jLCargo = new javax.swing.JLabel();
        jLRequisitos = new javax.swing.JLabel();
        jLVagas = new javax.swing.JLabel();
        jLEmpresas = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLNome = new javax.swing.JLabel();
        jLQtdeFunc = new javax.swing.JLabel();
        jLDescricao = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        tfDescricao = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        rbCargo = new javax.swing.JRadioButton();
        rbEmpresa = new javax.swing.JRadioButton();
        btnFiltrar = new javax.swing.JButton();
        btnMostrarTodos = new javax.swing.JButton();
        tfFiltro = new javax.swing.JTextField();
        jLSalario = new javax.swing.JLabel();
        tfSalario = new javax.swing.JTextField();
        jLCodigoEmp = new javax.swing.JLabel();
        tfCodEmp = new javax.swing.JTextField();
        tfFuncionarios = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rbRequisitos = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(300, 300));

        jLMayaJobs.setFont(new java.awt.Font("Uroob", 1, 36)); // NOI18N
        jLMayaJobs.setForeground(new java.awt.Color(255, 255, 255));
        jLMayaJobs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLMayaJobs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Safeimagekit-resized-img.png"))); // NOI18N
        jLMayaJobs.setText("MayaJobs");
        jLMayaJobs.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLMayaJobs.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLMayaJobsPropertyChange(evt);
            }
        });

        jTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTabela.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTabela.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTabela);

        tfCodigo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tfCodigo.setEnabled(false);
        tfCodigo.setInheritsPopupMenu(true);
        tfCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCodigoActionPerformed(evt);
            }
        });

        tfCargo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tfRequisitos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLCodigo.setForeground(new java.awt.Color(255, 255, 255));
        jLCodigo.setLabelFor(tfCodigo);
        jLCodigo.setText("CÓDIGO");

        jLCargo.setForeground(new java.awt.Color(255, 255, 255));
        jLCargo.setLabelFor(tfCargo);
        jLCargo.setText("CARGO");

        jLRequisitos.setForeground(new java.awt.Color(255, 255, 255));
        jLRequisitos.setLabelFor(tfRequisitos);
        jLRequisitos.setText("REQUISITOS");

        jLVagas.setBackground(new java.awt.Color(102, 0, 255));
        jLVagas.setFont(new java.awt.Font("Uroob", 0, 24)); // NOI18N
        jLVagas.setForeground(new java.awt.Color(255, 255, 255));
        jLVagas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLVagas.setText("VAGAS");

        jLEmpresas.setFont(new java.awt.Font("Uroob", 0, 24)); // NOI18N
        jLEmpresas.setForeground(new java.awt.Color(255, 255, 255));
        jLEmpresas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLEmpresas.setText("EMPRESAS");

        jLNome.setForeground(new java.awt.Color(255, 255, 255));
        jLNome.setLabelFor(tfNome);
        jLNome.setText("NOME");

        jLQtdeFunc.setForeground(new java.awt.Color(255, 255, 255));
        jLQtdeFunc.setLabelFor(tfFuncionarios);
        jLQtdeFunc.setText("QTDE FUNCIONÁRIOS");

        jLDescricao.setForeground(new java.awt.Color(255, 255, 255));
        jLDescricao.setLabelFor(tfDescricao);
        jLDescricao.setText("DESCRIÇÃO");

        tfNome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tfDescricao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnSalvar.setText("Salvar");
        btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnExcluir.setEnabled(false);
        btnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExcluirMouseClicked(evt);
            }
        });
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar Tudo");
        btnLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimparMouseClicked(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Filtrar por:");

        grupoBotao.add(rbCargo);
        rbCargo.setForeground(new java.awt.Color(255, 255, 255));
        rbCargo.setText("Cargo");
        rbCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCargoActionPerformed(evt);
            }
        });

        grupoBotao.add(rbEmpresa);
        rbEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        rbEmpresa.setText("Nome");
        rbEmpresa.setAutoscrolls(true);
        rbEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEmpresaActionPerformed(evt);
            }
        });

        btnFiltrar.setText("Filtrar");
        btnFiltrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFiltrarMouseClicked(evt);
            }
        });
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        btnMostrarTodos.setText("Mostrar todos");
        btnMostrarTodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostrarTodosMouseClicked(evt);
            }
        });

        tfFiltro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLSalario.setForeground(new java.awt.Color(255, 255, 255));
        jLSalario.setText("SALÁRIO");

        tfSalario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tfSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSalarioActionPerformed(evt);
            }
        });

        jLCodigoEmp.setForeground(new java.awt.Color(255, 255, 255));
        jLCodigoEmp.setText("CÓDIGO");

        tfCodEmp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tfCodEmp.setEnabled(false);

        tfFuncionarios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tfFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFuncionariosActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Empresa");

        grupoBotao.add(rbRequisitos);
        rbRequisitos.setForeground(new java.awt.Color(255, 255, 255));
        rbRequisitos.setText("Requisitos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLMayaJobs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLVagas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLEmpresas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSeparator3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSalvar)
                        .addGap(33, 33, 33)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLCargo)
                                .addGap(42, 42, 42)
                                .addComponent(tfCargo))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLCodigo)
                                    .addGap(36, 36, 36)
                                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLRequisitos)
                                    .addComponent(jLSalario))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfSalario)
                                    .addComponent(tfRequisitos))))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLCodigoEmp)
                                .addGap(21, 21, 21)
                                .addComponent(tfCodEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLNome)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLQtdeFunc)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tfFuncionarios))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLDescricao)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbCargo)
                                .addGap(18, 18, 18)
                                .addComponent(rbEmpresa)
                                .addGap(5, 5, 5)
                                .addComponent(jLabel2))
                            .addComponent(rbRequisitos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnFiltrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnMostrarTodos))
                            .addComponent(tfFiltro))))
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLMayaJobs)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLVagas)
                    .addComponent(jLEmpresas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLCodigo))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLCodigoEmp)
                            .addGap(4, 4, 4)))
                    .addComponent(tfCodEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLCargo)
                    .addComponent(jLNome)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLRequisitos)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfRequisitos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLQtdeFunc)
                        .addComponent(tfFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLSalario)
                        .addComponent(tfSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLDescricao)
                        .addComponent(tfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnExcluir)
                    .addComponent(btnLimpar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rbCargo)
                    .addComponent(rbEmpresa)
                    .addComponent(tfFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMostrarTodos)
                            .addComponent(btnFiltrar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbRequisitos)))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLMayaJobsPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLMayaJobsPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLMayaJobsPropertyChange

    private void tfCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCodigoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void rbCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCargoActionPerformed

    private void jTabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelaMouseClicked
        tfCodigo.setText(jTabela.getValueAt(jTabela.getSelectedRow(), 
                MayaJobsTableModel.COL_COD_VAGA).toString());
        tfCargo.setText(jTabela.getValueAt(jTabela.getSelectedRow(), 
                MayaJobsTableModel.COL_CARGO).toString());
        tfRequisitos.setText(jTabela.getValueAt(jTabela.getSelectedRow(), 
                MayaJobsTableModel.COL_REQUISITOS).toString());
        tfSalario.setText(jTabela.getValueAt(jTabela.getSelectedRow(), 
                MayaJobsTableModel.COL_SALARIO).toString());
        tfCodEmp.setText(jTabela.getValueAt(jTabela.getSelectedRow(), 
                MayaJobsTableModel.COL_COD_EMP).toString());
        tfNome.setText(jTabela.getValueAt(jTabela.getSelectedRow(), 
                MayaJobsTableModel.COL_NOME).toString());
        tfFuncionarios.setText(jTabela.getValueAt(jTabela.getSelectedRow(), 
                MayaJobsTableModel.COL_QTDE_FUNC).toString());
        tfDescricao.setText(jTabela.getValueAt(jTabela.getSelectedRow(), 
                MayaJobsTableModel.COL_DESCRICAO).toString());
        btnExcluir.setEnabled(true);
        
    }//GEN-LAST:event_jTabelaMouseClicked

    private void tfFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFuncionariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFuncionariosActionPerformed

    private void tfSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSalarioActionPerformed

    private void btnLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimparMouseClicked
        this.limparCampos();
    }//GEN-LAST:event_btnLimparMouseClicked

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
   
    }//GEN-LAST:event_btnSalvarMouseClicked

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(tfCargo.getText().trim().equals("") || tfRequisitos.getText().trim().equals("") || 
                tfSalario.getText().trim().equals("") || tfNome.getText().trim().equals("") || 
                tfFuncionarios.getText().trim().equals("") || tfDescricao.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos.",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
        } else {
            vagas = new VagasEmpregos();
            vagas.setCargo(tfCargo.getText());
            vagas.setRequisitos(tfRequisitos.getText());
            vagas.setSalario(Float.parseFloat(tfSalario.getText()));
            
            Empresas emp = new Empresas();
            emp.setNome(tfNome.getText());
            emp.setQtdeFuncionarios(Integer.parseInt(tfFuncionarios.getText()));
            emp.setDescricao(tfDescricao.getText());
            
            vagas.setEmpresa(emp);
            
            if(tfCodigo.getText().equals("") && tfCodEmp.getText().equals("")){
                daoVagas.inserirBanco(vagas);
            } else {
                vagas.setCod_vaga(Integer.parseInt(tfCodigo.getText()));
                emp.setCodigo_emp(Integer.parseInt(tfCodEmp.getText()));
                daoVagas.alterar(vagas);
                
            }
            this.atualizarTabela();
            this.limparCampos();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnFiltrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFiltrarMouseClicked
        String campo = "";
        if(rbCargo.isSelected()){
            campo = "cargo";
        } else if(rbEmpresa.isSelected()) {
            campo = "nome";
        } else {
            campo = "requisitos";
        }
        
        jTabela.setModel(new MayaJobsTableModel(daoVagas.buscarTodosFiltro(campo, tfFiltro.getText())));
       
    }//GEN-LAST:event_btnFiltrarMouseClicked

    private void btnMostrarTodosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarTodosMouseClicked
        this.atualizarTabela();
    }//GEN-LAST:event_btnMostrarTodosMouseClicked

    private void btnExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseClicked
        int confirma = JOptionPane.showConfirmDialog(null, "Confrma a exclusão?",
            "Exclusão de Vaga", JOptionPane.YES_NO_OPTION);
        
        if(confirma == 0){
            daoVagas.excluir(Integer.parseInt(tfCodigo.getText()));
            this.limparCampos();
            this.atualizarTabela();
        }
        
    }//GEN-LAST:event_btnExcluirMouseClicked

    private void rbEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbEmpresaActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFiltrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MayaJobs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MayaJobs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MayaJobs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MayaJobs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MayaJobs().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnMostrarTodos;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup grupoBotao;
    private javax.swing.JLabel jLCargo;
    private javax.swing.JLabel jLCodigo;
    private javax.swing.JLabel jLCodigoEmp;
    private javax.swing.JLabel jLDescricao;
    private javax.swing.JLabel jLEmpresas;
    private javax.swing.JLabel jLMayaJobs;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLQtdeFunc;
    private javax.swing.JLabel jLRequisitos;
    private javax.swing.JLabel jLSalario;
    private javax.swing.JLabel jLVagas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTabela;
    private javax.swing.JRadioButton rbCargo;
    private javax.swing.JRadioButton rbEmpresa;
    private javax.swing.JRadioButton rbRequisitos;
    private javax.swing.JTextField tfCargo;
    private javax.swing.JTextField tfCodEmp;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfDescricao;
    private javax.swing.JTextField tfFiltro;
    private javax.swing.JTextField tfFuncionarios;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfRequisitos;
    private javax.swing.JTextField tfSalario;
    // End of variables declaration//GEN-END:variables
}
